"use client";

import React from "react";
import { useParams, useRouter } from "next/navigation";
import CATEGORYs from "@/components/helper/CATEGORYs";
import Follow from "@/pages/Category/Social_Links";
import RecentPost from "@/pages/Category/RecentPost";
import CategorysList from "@/pages/Category/CategorysList";

import Category_Post from "../Category/Category_Post";

export const metadata = {
  title: "Travel Itinerary - Travel Tippler",
  description: "Generated by create next app",
};

const Itinerary = () => {
  return (
    <div className="md:flex md:justify-between mx-[5%] md:mt-2 ">
      <div className="bg-white ">
        <div className="mt-4 ">
          <h1 className="text-[19px]  font-semibold ml-[2%]">Travel Itinerary</h1>
          <hr className="mx-[4px] " />
        </div>
        {CATEGORYs.map((category, index) => {
          if (category.category === "Travel Itinerary") {
            return <Category_Post id={category.id} key={category.id} description={category.detail.description} date={category.date} image={category.image} category={category.category} aurther={category.aurther} heading={category.heading} />;
          }
          return null;
        })}
      </div>
      <div className="sm:w-[35rem] mt-2">
        <Follow />
        <RecentPost />
        <CategorysList />
      </div>
    </div>
  );
};

export default Itinerary;
