import Banner from "@/pages/Home/Banner";
import React from "react";

export const metadata = {
  title: "Travel Tippler -",
  description: "Generated by create next app",
};

const Home = () => {
  return <div>
    <Banner/>
  </div>;
};

export default Home;
