import React from 'react'

export const metadata = {
  title: "Travel Itinerary - Travel Tippler",
  description: "Generated by create next app",
};

const Itinerary = () => {
  return (
    <div>Itinerary</div>
  )
}

export default Itinerary