
import React from "react";
import ItineraryPage from "@/pages/Itinerary/Itinerary";

export const metadata = {
  title: "Travel Itinerary - Travel Tippler",
  description: "Generated by create next app",
};

const Itinerary = () => {
  return (
    <>
      <ItineraryPage />
    </>
  );
};

export default Itinerary;
