import React from 'react'

// export const metadata = {
//   title: "Travel Tippler -",
//   description: "Generated by create next app",
// };

const WebStory = () => {
  return (
    <div>Web Story</div>
  )
}

export default WebStory